### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by sbycrosz** [tachyons-css/react-native-style-tachyons#34]
Hi @fab1an ! Big thanks for the library!

Any plan for including tachyon's positioning styles (`top-0`, `bottom-0` etc.) ? 
Would you accept a PR for that?

-Sam

**Comment by fab1an** [comment]
RNT already contains [`absolute-fill`](https://github.com/tachyons-css/react-native-style-tachyons#heights--widths). Do you need more than that?

**Comment by andreyluiz** [comment]
I need the same feature, because I need to change the bottom position, for example: `bottom: 10`.

**Comment by fab1an** [comment]
So you have an absolutely positioned `View`. Can you help yourself with bottom padding, e.g. `pb2`?

**Comment by sbycrosz** [comment]
I don't think so :( 
I know that `absolute-fill` will fill the entire screen with the view, but sometime you don't want that e.g. to have a floating submit button on the bottom of the screen

**Comment by fab1an** [comment]
I'm conflicted about this issue.

I could add `left-0`, `right-0` etc., which would set `position: absolute` and the space.
I'm not sure though, whether other flexbox properties like `flx-i` continue to work on such an element, could you test that out?

For different spacings than 0, I would have to add steps at the scale like `ml1`, `ml2`, since I don't want arbitrary values in RNT's API. How should those be named `left-1`, `left-2`, `left-4`, `left-8`?

Also we then have two different ways of specifying layouts, which just increases the API surface.

Nested layout containers are performance wise for free in React-Native, so what's the downside of wrapping your floating button inside an `absolute-fill` with `padding` set to some value?

Thoughts welcome!

**Comment by sbycrosz** [comment]
I'm thinking of just porting these style from tachyons-css

```
.absolute position:absolute
```

And the positioning styles such as:
```
.left-0 left: 0
.left-1 left: 1rem
.left--1 left: -1rem
```

Cheers!

**Comment by fab1an** [comment]
If everything above the button is part of the upper screen, which is child to the absolute screen, it shouldn't disable any interaction. A transculent screen might work as well.

I will add `left-0`, `left-1` like you proposed.

**Comment by sbycrosz** [comment]
Thanks @fab1an !

**Comment by fab1an** [comment]
You're welcome. I didn't implement the negative values btw, because I didn't know how to name them in the manual style object.
