### ISSUE TITLE
How to change scales

### ISSUE THREAD

**Issue by osikes** [tachyons-css/react-native-style-tachyons#71]
Is there a way to override the height and width rem scales?

**Comment by fab1an** [comment]
Why would you want to do that?

**Comment by sbycrosz** [comment]
In our case, we use the [8-point grid system](https://builttoadapt.io/intro-to-the-8-point-grid-system-d2573cde8632) on most of our products, so we added some half steps (e.g. pa35 = 1.5rem)

**Comment by osikes** [comment]
This is essentially the issue for my company as well, designers want half steps. Not just power 2.

**Comment by fab1an** [comment]
I had this issue in applications as well, but I usually just created an object or class where i used the exported `sizes` from tachyons to specify special dimensions:

```javascript
import { sizes } from "react-native-style-tachyons"
const AppWidths = {
    iconCell: sizes.w2 + sizes.w1 
}
```

Combine this with `flx-i` at the right places, and I reckon that most use-cases will be covered.

I'm open for discussion, but in general I want to avoid opening the default-tachyons-scale, since it works very well. The users who need special widths could also write a react-wrapper.
