### ISSUE TITLE
Additional elements

### ISSUE THREAD

**Issue by jbrodriguez** [tachyons-css/react-native-style-tachyons#8]
@fab1an I switched my app entirely to native tachyons and it's working awesomely.

I'm currently inlining a couple of properties that are not available:

- **StyleSheet.hairlineWidth**: no bl|br|bt|bb equivalent
- **size**: some components (notably react-native-vector-icons) need a size property, it would be nice to have something based on rems
- **border[Top|Bottom|Left|Right]Color**: this I can do in my app, since colors are separate
- **0.5 height/width**: is there no room for them ? :)

In any case, this is the way styling should be done.

Really great library !

**Comment by fab1an** [comment]
> StyleSheet.hairlineWidth: no bl|br|bt|bb equivalent

I'm thinking about replacing bl|br|bt|bb to specify `borderWidth: StyleSheet.hairlineWidth` instead of `1`. Or is that too small?

> size: some components (notably react-native-vector-icons) need a size property, it would be nice to have something based on rems

Thinking about this, have you tried setting a font class on the icons though? 

> border[Top|Bottom|Left|Right]Color: this I can do in my app, since colors are separate

I think this is too rarely needed in order to be useful, but thinking about it.

> 0.5 height/width: is there no room for them ? :)

The reason for this is that a scale by the power of two always results in integers, therefore has no rounding errors and everything will always line up. If you introduce `0.5rem` you get situations where two elements are off one pixel, and we want to avoid that ;).

I haven't felt the need for `width: 0.5rem` yet, can you work around it?
Is your app a game or something. All of this sounds highly visual to me.

**Comment by jbrodriguez** [comment]
> I'm thinking about replacing bl|br|bt|bb to specify borderWidth: StyleSheet.hairlineWidth instead of 1. Or is that too small?

That should be fine. You could always have a ```<View style={{width=xxx}} />```

> Thinking about this, have you tried setting a font class on the icons though?

I'll check that out

> Is your app a game or something? All of this sounds highly visual to me.

It's kind of a dashboard, so it has many different visual widgets

> I haven't felt the need for width: 0.5rem in my fairly complex App yet, can you work around it?

Yes, I'm looking at alternatives :)

**Comment by fab1an** [comment]
I checked out using `hairlineWidth` for border, but it's too small in my opinion, to be the default.

**Comment by fab1an** [comment]
@jbrodriguez Did setting `f5` or something on the `<Icon>`s work?

Also: I'm thinking about introducing `bt--green` etc. for the different border-colors, but are you sure they're necessary? I want to keep the library minimal to help people make good designs.

**Comment by jbrodriguez** [comment]
@fab1an fontSize works on the icons.

The bt--green, etc are really too much.

Closing this issue now 👍

**Comment by fab1an** [comment]
Ok, let me know if you have further input!
